name: Create Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: "Release"
  cancel-in-progress: false

jobs:
  build-and-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node ${{ vars.NODE_VERSION }} Environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install the vsce npm package
        run: |
          npm install
          npm install -g @vscode/vsce

      - name: Package the extension pack
        run: |
          vsce package

      - name: Read package.json
        uses: krstphrrr/package-json-version-reader@v1.0.0
        id: package-version
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.version }}
          name: Release ${{ steps.package-version.outputs.version }}
          body: |
            **Version**: ${{ steps.package-version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            platforce-sf-ext-pack-${{ steps.package-version.outputs.version }}.vsix
